# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Creating Alpha Build"
  lane :alpha do
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:664303562449:android:1e7421ff16ebd97ba3dff0",
      service_credentials_file: "./firebase_credentials.json")

    
      version_code= latest_release[:buildVersion]

      build_number= get_updated_version_number(latest_release[:displayVersion])

      sh "flutter clean"
      sh "flutter pub get"
      sh "flutter build apk --release --build-number=#{version_code} --build-name=#{build_number} --no-tree-shake-icons"
      
      firebase_app_distribution(
            app: "1:664303562449:android:1e7421ff16ebd97ba3dff0",
            groups: "qa-tester",
            release_notes: "bug fixes",
            service_credentials_file: "./firebase_credentials.json",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk"  
      )


  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
def get_updated_version_number(build_number)
  # Splitting with "-"
  split_parts = build_number.split("-")
  first_index = split_parts.first

  # Splitting with "."
  version_parts = first_index.split(".")
  last_part = version_parts.last.to_i + 1

  # Reconstructing the string
  version_parts[-1] = last_part.to_s
  build_number = version_parts.join(".")
  build_number
end